scripts/pranay-yengandula.py
Pranay Yenagandula ID HNG-01542
=> Pranay Yenagandula HNG-01542

scripts/Mohammed Kabir Hussaini.php, scripts/abdulkarim-sarumi.py
=> Pull request from abdulkarim.sarumi

scripts/Ifedayo-Adeniyi.py
=> Ifedayo's HNG task

scripts/isaac-adariku.dart
=> commit isaac-adariku.dart

scripts/moses-aizee.js
Please marge my request... Thanks. You guys are amazing.
=> Moses Aizee added his file

scripts/damilola-oseni.js
=>  chore: added a js script for stage 2 task

scripts/Nwanozie-Promise.php
=> nwanozie promise

scripts/Razeb-Enyi.js
=>  Razeb-Enyi.js

scripts/edwin-kayang.js
=> Added file

scripts/esther-ninyo.js
=> ninyo's initial commit

scripts/habeeb-awoyemi.js
please check my PR and merge, thank you.
=> added habeeb awoyemi to the script file

scripts/Munachimso-ike.py
=> Added my script including my personal information

scripts/sanusi-victor.js
Good evening guys. I just added my own script. I used Javascript. Thanks
=> submitting my own script

scripts/Helen-Jonathan.js
A pull request for task for stage 2
=> fill from Helen Jonathan added.

scripts/abdullah-momoh.php
Please merge my pull request. I just added my file to the pull request. Thanks!!!!
=> Abdullah Momoh added a new file to the scripts folder

scripts/Mustapha-Raji.js
=> Mustapha Raji

scripts/abisola-morohunfolu.js
I added my own named file in js
=> Added-Abisola-Morohunfolu-file

scripts/Eyimofe-ogunbiyi.js
=> script initial commit

scripts/sunday-orimoyegun.js
=> starday committed HNGi7 task

scripts/dev-quie.php
=> stage 2 task

scripts/adeoluwa-adetoyese.py
=> adeoluwa-adetoyese commit

scripts/Nwanozie-Promise.php
=> Nwanozie-Promise Updated

scripts/Adetola-Adeyeye.java
=> Adetola-Adeyeye.java

scripts/toluwaleke-ogidan.py
i am tolu and i just added my python script
=> my HNG script

scripts/Nwanozie-Promise.php
=> Nwaozie-promise passed

scripts/Igwe-Daniel.py
please merge i have added my script
=> Igwe Daniel task2 script

scripts/ahmed-khaled.js
=> adding my intro js file

scripts/Adetola-Adeyeye.java
Reverts elishaukpong/HNG-Script#99
=> Revert "Update Adetola-Adeyeye.java"

scripts/ugonna-erondu.py
=> Script added

scripts/tola-shobowale.php
Tola Shobowale with HNGi7 ID HNG-00272
=> tola-shobowale Hng script

scripts/bolarinwa-kazeem.js
Here is mine
Bolarinwa Kazeem.
Team-Sentry
=> Add bolarinwa-kazeem.js

scripts/sanusi-victor.js
My status failed so i have removed the . from my script. thanks
=> removed the full stop from my output

scripts/paul-oisamoje.php
=> commit paul-oisamoje

index.php
=> json format

scripts/semiu-biliaminu.php
=> added a file

index.php
=> fix repeatition of names

scripts/alexander-domakyaareh.js
=> HNG script

scripts/Razeb-Enyi.js, scripts/Razeb-Enyi.py
=> Update Razeb-Enyi.py to Razeb-Enyi.js

scripts/olufemi-fadahunsi.js
Created variables and assigned my name and surname. Called the variables in console.log along with other text.
=> Added Olufemi Fadahunsi

scripts/damilola-oseni.js
=> chore: made changes to the file

scripts/Adebare-Amos.js
Please, kindly merge as I'm using my phone to code.
Thanks and well done guys
=> Created Adebare-Amos.js

scripts/Daniel-Igwe.py, scripts/Igwe-Daniel.py
renamed my script file and fixed errors causing script failure
=> renamed igwe-daniel.py to daniel-igwe.py and fixed script error

scripts/osinaya-oludare.js
=> osinaya oludare

scripts/Tobi-Osimosu.js
=> updated Tobi-Osimosu

scripts/Riliwan-Hassan.js
=> Initial commit

scripts/Tobi-Osimosu.js
=> updated Tobi-Osimosu.js

index.php
=> Count pass and fails

scripts/Daniel-Igwe.py
refactored my script to fix errors causing script failure
=> refactored my script

scripts/dev-quie.php
=> stored names in var

scripts/adewale-obidairo.js
Please kindly my script. Thanks
=> I just added my script

scripts/moises-borracha.php
=> Adding Moises's file

scripts/akerele-babatunde.js
=> PR for stage 2 task

scripts/jackson-jonah.php
Hello World  Script by Jonah Jackson
=> Hello World script

scripts/Simeon-Udoh.js
Adds my script to the `scripts` folder.
=> Added my script to the scripts folder

scripts/kayode-omotehinse.js
I have created the javascript file to console log the require information
=> kayode-omotehinse.js created

Mariam-Ismael-Saka.js, Mariam-Ismael.js
=> File Commit

scripts/Yusuf-Akinpeju.js
=> Akinpeju Yusuf Submission

scripts/chukwuemeka-ndubuisi.js
=> sumitted my js task

scripts/celestine-okonkwo.py
My script was similar to another.
=> Edited celestine-okonkwo.py

scripts/fahd-mohammed.js
Here is the submission for the completion of task 1. Team Sentry.
=> Fahd task 1 commit

scripts/emmanuel-ikwuoma.js
This script is based on Nodejs, and i used **http** core module to stream the responses.
=> added script emmanuel-ikwuoma.js

scripts/michael-olowe.py
=> added michael-olowe.py file

scripts/esther-ninyo.js
remove full stop, added semi-colon and i added HNG to my ID
=> changes made

scripts/raiyan-mukhtar.py
=> Adding my script 

scripts/sylvanus-jerome.php
i think the team is progressing.
=> just commit mine

scripts/Philip-akpan.js
Addition of js file from Philip Akpan
=> first commit made after add js file

scripts/alaneme-ikenna.js
=> my first commit for alaneme ikenna

scripts/abisola-morohunfolu.js
=> edited-my-script

scripts/egekenze-kelechi.py
=> Keicee32 made a commit

index.php, scripts/Adetola-Adeyeye.java, scripts/Adetola_Adeyeye.java
@elishaukpong dart has been added
=> dart added

scripts/jemimanaomi-ben.php
This is the script i tested and it passed.
=> Final task2 commit

Najeeb-Sulaiman.js, scripts/Najeeb-Sulaiman.js
I have committed my script as regards HNGi7 stage 2 task. Please verify and merge. Thank you.
=> Najeeb Sulaiman

scripts/Fongang-Rodrique.js
=> Added Fongang Rodrique to Script 

scripts/Edori-Atiri.js
=> I've added my script to the scripts folder

scripts/Nusrah-Farri-Ghazal.py
The reason my test was failing was because of the hyphen in my last name "Farri-Ghazal". It only returned true when i put "FarriGhazal" instead. Kindly see if this can be fixed, there are others with compound lastnames like mine.
=> Tested locally and returns true

scripts/Progress-Eze.js
=> added progress-eze.js file among the scripts

scripts/Yusuf-Akinpeju.js
=> Akinpeju Yusuf re-submission

scripts/Kehinde-Yusuf.js
completed the task for HNGi7 stage 2. this is Kehinde Yusuf pull and marge
=> added kehinde yusuf

oluwole-dada.js, scripts/Oluwole-Dada.js
I added my script to the `scripts` folder.
=> Added my script to scripts folder

scripts/emmanuel-ikekwere.js
=> This is my HNG Stage 2 task!

scripts/Tobi-Sangosanya.js
=> Task upload

scripts/Pranati.py
=> Added file for task

scripts/Moses-Benjamin.js
I just created a pull request. Please merge my work. Thank you
=> Adding my work

scripts/stvyn.js
Added my script for the Task 1 of the HNG internship
=> Added Stephen's script code for Task 1

scripts/Philip-akpan.js
=> Philip-akpan.js

scripts/olufemi-fadahunsi.js
After my script failed, I updated the name to remove my initial. It subsequently passed upon Xamp Test.
=> Updated name

.vscode/launch.json, scripts/awa-felix.dart
code is written in dart. code runs. and also passes the php test when i checked.
=> awa felix hng task 2

scripts/Tobi-Osimosu.js
I didn't declare a variable before, that's why it was failing. it should Pass now
=> re-editted Tobi-Osimosu.js

scripts/Mannan-Bansal.js
It's my stage2 task javascript file with the required output.
=> Stage2 task script by mbgamer28

maryam-mudasiru.js
=> Anita-Idemudia.js

scripts/lucas-okafor.js
=> lucas okafor

scripts/wisdom-ojiakor.js
=> Added wisdom Ojiakor

scripts/Abdulrasheed-Adediran.js
Abdulrasheed (HNG-02383)- Submission for stage 2 task.
=> 02383.Abdulrasheed.js

scripts/Emma-Omingo.js
:emma.omingo@riarauniversity.ac.ke
=> myJavascript Commit

Eboreime-rhoda.js
=> Created Eboreime-rhoda.js

scripts/Akash-Prasher.js
I'm using the arrow for creating function and calling it to console.log my details.
=> Adding details using function

scripts/John_Philip.js
=> stage 1 task commit

scripts/emmanuel-olowu.py
=> Emmanuel Olowu

scripts/Divakaran-T.py
Here the script for Stage 2 Task !!
=> Divakaran-T.py

scripts/George-Uweh.js
Added George-Uweh.js to scripts folder. Please merge.
=> Added George-Uweh.js

scripts/grenalyn.js
Add new member- to the script folder
=> add new member to script folder

scripts/Yusuf-Akinpeju.js
=> updating file for Yusuf

scripts/Sunday Okoromi.js
=> Create Sunday Okoromi.js

scripts/Oluwole-Dada.js
=> Added email to my script

scripts/claire-munyole.js
=> inital commit

scripts/Anyankah_Netochukwu.js
I created an (Anyankah_Netochukwu.js) file.
This was done using arrays.
=> I worked on the task using javascript (Anyankah_Netochukwu.js)

Emmanuel-Nwachukwu.py, scripts/Emmanuel-Nwachukwu.py
I added my file to script ..Thank you
=> Kindly Verify

chidubem-nwigwe.java
The code prints out a message that states my name, HNG-i7 ID number and language of choice.
=> My first Java script!

scripts/Emmanuel-John.js
@elishaukpong please review thanks
=> I have added my task 

scripts/chidubem-nwigwe.java
The code prints out a message that states my name, HNG-i7 ID and language of choice.
=> My First Commit!

Busayo-Olushola.py
Hello, I just made some changes, and would like to delete the previous file: Busayo Olushola.py to Busayo-Olushola.py
=> Busayo-Olushola Final

scripts/okorie-nnamdi.js
i just joined the team so i have added my scripts.
=> first commit

scripts/Bolaji-Ola.js, scripts/Ogheneovie-Oki-Peter.js
Added my script named Ogheneovie-Oki-Peter.js
=> Added my Script

scripts/Folorunso-tolulope.js, scripts/Kehinde-Yusuf.js
=> done and pass

scripts/faruk-adekola.js
=> Faruk Adekola Scriot

scripts/Victor-Shigaba.js
=> Created script

scripts/Precious-Ndigwe.js
Hello team lead and everyone working on this task to make it a success. You're all doing well, more grease to your elbows. Kindly add my script. 
Thanks
=> Create Precious-Ndigwe.js 

scripts/Olabisi-Olawale.js
i have worked on it and made it output without ("")
=> olabisi-Olawale.js

scripts/Boluwaji-Osakinle.js
=> HNGi7 task 2 init

scripts/Chukwudi-Ochuenwike.js
I created a new file Chukwudi-Ochuenwike.js and made my commit
=> added a new file - Chukwudi-Ochuenwike.js to script

Busayo Olushola.py
I just reviewed my code now, please, confirm
=> Update Busayo Olushola.py

scripts/annah-nichola.js
created a script and pushed it,
=> added my file

scripts/Karen-Efereyan.js, scripts/barnabas-asha.js
=> added email

scripts/moses-aizee.js
Please treat kindly.. You guys are doing an amazing job.
=> Added my email as directed

scripts/azeez-okelabi.php
=> Added email as instructed

scripts/Obafunmilayo-Lijadu.py
=> Updated scripts

scripts/susan-wangari.js
JavaScript code to get name,hng id and email
=> a script to get name,hng id and email address

scripts/sylvanus-jerome.php
=> updated file with email address

scripts/damilola-oseni.js
=> chore: updated with my email address

scripts/Nwanozie-Promise.php
=> nwanozie-promise mail added

scripts/Nelson-Chinedu, scripts/nelson-chinedu
=> Nelson Chinedu commits 

scripts/AlexanderUgwuanyi.js
Task2 Script Completed. Email Added.
=> Task2 Script Completed. Email Added.

scripts/anash-uddin.js
My task-2 submission in Javascript.
=> Added JS file for task-2

scripts/opeyemi-popoola.js
Added ```opeyemi-popoola.js``` file containing HNG assignment to the script folder for assessment. Also added my email to the js file.
=> Created and updated Js file with required information.

scripts/Tochukwu-Onwunali.js
=> Added email to script

scripts/Chukwudi-Ochuenwike.js
I added my email to the my script file
=> included email to the output

scripts/Boluwaji-Osakinle.js
=> HNG-04673 email updated

scripts/Oke-olalekan.js
Modified the name.js file to include email in the output.
=> updated file; email added

scripts/Olabisi-Olawale.js
email added in specified format.
=> added Email address to the output

scripts/the_algorithmist.py
I have added my python script 'the_algorithmist.py' to the scripts/ dir
=> Added my py Script- the_algorithmist

scripts/Mannan-Bansal.py
I have edited my code and added email
=> Added email to existing working code by mbgamer28

scripts/sangobiyi-titiayo.js
=> Included email to the script  sangobiyi

scripts/Bakare_yusuf.php
i just added the email address as directed
=> Adding email address to my script

scripts/Charles-Magbo.js
=> added user Email

scripts/Jennifer-Onyeama.php
=> Added a PHP Script

scripts/moises-borracha.php
=> Adding Moises's email to it

scripts/Augusta-Ehihebolo.js
=> AugustaEhihebolo details commit

scripts/henry-mutegeki.js
It simply adds my js script that conforms to the team task assignment. 
I have added the email so my output conforms to the latest instructions. I would advise that if the parser is not up to date to check for email, then my PR can wait.
I run it in my local environment and browser 
This shows the output when I
run it in the browser
=> feat: add henry script for team task [Has email]

scripts/murtala-aliyu.js
please check out  my javascript file pull request pull request. thank you
=> murtala Aliyu's jsvavscript file

scripts/nerona-sook.py
Nerona Sook
neronasook@gmail.com
HNG-00194
=> Added python script.

scripts/bolarinwa-kazeem.js
I updated the code with my email as advised.
=> bolarinwa-kazeem.js email update

scripts/habeeb-awoyemi.js
i just updated my email inside the habeeb-awoyemi.js script, please merge my pull request
=> adding email for habeeb awoyemi javascript script

scripts/murtala-aliyu.js
please check out  my javascript file pull request. thank you
=> added a missing semi colon

scripts/Moses-Benjamin.js
Please merge mp PR. I just added email to my script file.Thanks
=> Added email address

scripts/Ogheneovie-Oki-Peter.js
added email in the format specified in my file titled Ogheneovie-Oki-Peter.js
=> added email 

scripts/okereke-okereke.py
Hi,
I've included my email address in my task script for the Stage 2 Task.
Thanks.
=> Include task script for Okereke

scripts/michael-olowe.py
edited michael-olowe.py file(added email)
=> edited michael-olowe.py file(added email)

scripts/Daniel-Igwe.py
updated my script (daniel-igwe.py) to include my email
=> updated my script (daniel-igwe.py) to include my email

scripts/Adeyemi-Matthew.py
Hello there, this is My Updated Pull request with my email.
=> This is my Update of my Email. Adeyemi-Matthew.py

scripts/annah-nichola.js
hello, have added a email to the script
=> added my email to the script

scripts/alexander-domakyaareh.js
=> HNG script email

README.md
Add a clear instruction on adding intern script to prevent creating files in the project root directory.
=> Update README Instructions

scripts/Emmanuel-John.js
@elishaukpong please review my pull request. Thanks
=> Updated my script with my email

scripts/farouk-afolabi.js
=> added my email address to stage 2 task

scripts/Adebayo-Pelumi.js
The correction has been made to my code to reflect the update
=> changes to reflect update

scripts/abdullahi.aliyu.js
Added file which displays my name and lastname. Sorry i submitted late, Broke my laptop screen so i had to borrow, from a non techie
=> Added my file 

scripts/wisdom-ojiakor.js
I made changes to my code and added my mail
=> added my mail

opeyemi-peter.js, scripts/Opeyemipeter.js
=> Opeyemipeter

scripts/Chinedu-Ijeomah.js
=> Javascript file commit for task 2

scripts/jackson-jonah.php
Fixed bug on email integration
=> Fix bug on email 

scripts/Victor-Shigaba.js
=> fixed script for task 2

scripts/fredrick-njeri.py
=> updated commit

Chinonso-Okafor.js, scripts/Chinonso-Okafor.js
=> pull request

.gitignore, scripts/Sifon-Isaac.js
=> stage 2 profile task

.vscode/settings.json, scripts/Abdulmalik-Quadri.js
Forked the repo and created my script, tested it and it passed the test
=> Added my script and my email

scripts/philemonbrain-Anagwu.py
=> Hng Task 2

scripts/Ridwan_Gbadamosi.php
=> Ridwan_Gbadamosi.php

scripts/Chinedu-Ijeomah.js
=> fix: Added email to the displayed message

scripts/jemimanaomi-ben.php
this is my updated task2 with email
=> Task2 with email commit

scripts/Kehinde-Yusuf.js, scripts/yusuf-kehinde.js
added email and changed name from kehinde-yusuf.js to yusuf-kehinde.js
=> changed name and added emali to yusuf-kehinde.js

scripts/olamide-agboola.js
Hi, this is Olamide Agboola task 1 for team sentry on HNGi7
Do let me know of any important feedback
Thanks.
=> Task 1 Completed

scripts/emmanuel-ikekwere.js
-I added my email to the original code.
=> Updated HNG Internship Stage 2 task.

scripts/Oladayo-Babalola.js
=> Updated email

scripts/sanusi-victor.js
Good day Guys. I just added my email address to the string we are supposed . Thanks.
=> added email to the output

nk-ugwu.py
print(“Hello World, this is Nk Ugwu with HNGi7 ID HNG-02568 using python for stage 2 task”)
=> Stage 2 task with python3

scripts/Folorunso-tolulope.js
=> fixed: email added

scripts/Dashua_Gamaliel.js
I humbly request to add my own script to meet requirements for promotion to stage 2. Weldone Sentry!
=> Team Sentry HNGi7 task 2

scripts/suyom-rolandjethro.js
Good day sir! I did my task sir. Thanks.
=> Added suyom-rolandjethro.js

scripts/areel007.js
Added a JS file that print out my name and some other details
=> added areel007.js to scripts folder

scripts/Yusuf-Akinpeju.js
=> Adding email

scripts/mariam-hamzat.js
This is a script file that displays my name, HNGi7 ID, my email and the language used to write this script and the stage task.
=> your commit here

scripts/emmanuel-ikekwere.js
I reviewed and updated the js script for the HNGi7 stage 2 task.
=> Updated refactored JS script.

scripts/heccubernny-HNG-03910.py
=> Heccubernny-HNG-03910 script

Fasakin-Ayomide.js, scripts/Fasakin-Ayomide.js
I've done all needful. Kindly merge
=> Fasakin-Ayomide.js

scripts/Nsikak_Akpan.java
=> Nsikak_Akpan.java with email

scripts/Tochukwu-Onwunali.js
=> Made script adjustments

scripts/emmanuel-erondu.php, scripts/emmanuel-erondu.py
New changes to comply with directives
=> updated changes to scripts (email)

scripts/kehindeBankole.js
Please merge my pull request sir ,thank you
=> Created my script and its output

scripts/Oke-olalekan.js
added spaces where necessary in the script so that it can pass.
=> HNGi7 task 2

scripts/Taiwo-Yusuf.js, scripts/Yusuf-Taiwo.js
Rectified surname and name order
=> Added Yusuf

scripts/anash-uddin.js
Made some changes in text as per the required format.
=> Updated output text

scripts/Hope-Okelue.py
=>  Team task

scripts/Emem-Etukudo.py
Added my script to scripts with the name - Emem-Etukudo.py
=> Teamsentry

scripts/Simeon-Udoh.js
=> Updated my script file as per the new requirement. 

scripts/michael-olowe.py
(modified michael-olowe.py file, changed script from hello world to Hello World)
=> (modified michael-olowe.py file, changed from hello world to Hello World)

scripts/Damilare-Olagbende.js
=> Updated Damilare-Olagbende.js

scripts/susan-wangari.js
=> made changes to the script

scripts/Adigun_samuel.js
=> Adigun_samuel.js

scripts/Opeyemi-peter.js, scripts/Opeyemipeter.js
=> opeyemi-peter

scripts/mariam-hamzat.js
This is a script which outputs my name, HNGi7 ID, email, language used for writing the script and the stage task
=> this is an updated script. i edited an error

scripts/Dashua_Gamaliel.js
Kindly merge to the master branch. This should work now, I have decided to keep the code simple this time.
=> made some changes in order to fix email output issue

scripts/stvyn.js
Added my email and updated my code.
=> Added my email field to the task.

Oluwaferanmi Michael.py, scripts/Oluwaferanmi Michael.py
=> Updated Script 

chukwuka-chimdindu.js
This is my script in javascript
=> chukwuka-chimdindu.js

scripts/alozieuwa-emmanuel.py
=> Alozieuwa Emmanuels task

scripts/oluwatimilehin-idowu.js
changed the structure of my file
=> changed the structure of my file

scripts/chukwuemeka-ndubuisi.js
=> made necessary corrections

scripts/habeeb-awoyemi.js
i just updated my script so that it can pass, i now use a function, hopefully this should pass, thanks
=> updated version of my script so that it can pass

scripts/Najeeb-Sulaiman.js
This is an update to the initial script submitted. I have added my email, please merge as soon as possible. Thanks.
=> Najeeb-Sulaiman.js

scripts/Nsikak-Akpan.java, scripts/Nsikak_Akpan.java
Nsikak_Akpan.java with email (second commit)
=> Nsikak_Akpan.java with email (second commit)

scripts/Oladayo-Babalola.js
=> Edited code for uniqueness

scripts/deborah-inyang.js
=> Fixed errors again

scripts/Nsikak-Akpan.java
Nsikak-Akpan.java with email (fourth commit)
=> Nsikak-Akpan.java with email (fourth commit)

scripts/habeeb-awoyemi.js
i just updated my task please check it out
=> updated task

scripts/promise-johnson.js
updated script file (promise-johnson.js)
=> updated script file (promise-johnson.js)

scripts/Ozioiza-Audu.py
=> Updated with email Ozioiza-Audu.py

scripts/grant-iloba.js
=> added grant-iloba.js file

NK-Ugwu.py, nk-ugwu.py
print('Hello World, this is Nk Ugwu with HNGi7 ID HNG-02568 and email egougwu11@yahoo.com using python for stage 2 task')
=> update with email

scripts/Joseph-obochi.js
=> edited joseph-obochi.js

scripts/oyelola-emmanuel.py
=> emmanoyelola@gmail.com

scripts/Olatubosun-John.php
=> Update on Olatubosun-John.php

scripts/aminat-okunuga.php
=> Created aminat-okunuga.php

scripts/thaddeus-ojike.py
Code was initially written with Python3. I was asked to rewrite code using python2. That has been done.
=> recoded with python 2

scripts/Munachimso-ike.py
=> "Added email address and failed test bug"

scripts/Udochi-Dikamsi.py
Added Udochi-Dikamsi Python Script
=> Added Udochi-Dikamsi Python Script

scripts/Omonigho-Oddiri.js
This is my HNG Task 2 response
=> My HNG Task 2

oladimeji-abiola.java, oladimeji-abiola.py
=> Oladimeji-Abiola.py

scripts/Gabriel Owusu.py
email: gabriel.owusu@ashesi.edu.gh
=> Update Gabriel Owusu.py

Tolulope-Kehinde.js, scripts/Tolulope-Kehinde.js
=> second task

scripts/abdulrafik.py
=>  stage 2 task

scripts/Oscar-Ekeyekwu.js
=> Ekeyekwu Oscar Task 1

index.php, scripts/dev-quie.php
Email added to personal script and buffering in index script.
=> Update on email

scripts/Egbekwu-Nwanedilobu.php
Please let me know if it passes. Thanks
=> Task Script

scripts/Emmanuel-John.js
@elishaukpong please review. Thanks
=>  changed the return statement to a console.log

scripts/annah-nichola.js
=> javascript function

scripts/Omonigho-Oddiri.js
I made the corrections on my code for the stage 2 task
=> Edited my code for Stage 2 task

scripts/habeeb-awoyemi.js
please check my request , thanks
=> habeeb awoyemi task

loyal-amaechi.js, scripts/loyal-amaechi.js
=> updated script

scripts/mariam-hamzat.js
This is a script which outputs my name, HNGi7 ID, email, language used for writing the script and the stage task
=> Pls merge my script 

scripts/omotayo-kasim.php
=> omotayokasim commit

scripts/Busayo Olushola.py
=> Delete Busayo Olushola.py

scripts/abolade-kasope.js
=> Merge my script for the stage 2 task

scripts/Christian-Nwachukwu.js
Christian Nwachukwu requested to merge.
=> Christian Nwachukwu HNG-00941 script

scripts/Abiodun-Olushola.js
Reverts elishaukpong/HNG-Script#1252
=> Revert "added hngi7"

scripts/abdullahi.aliyu.js
Removed the `:` from the code and added my language as a key
=> Updated my failed script

scripts/peter-onum.py
script from peter onum, username Champ
=> peter onum added a script

scripts/osondu-tochukwu.js
I made a Correction on My Name. Please Accept.
=> I made a Correction on My Name. Please Accept.

scripts/eric-ibu.js
This PR  commits a task script for intern HNGi 7 ID: 04677, Ibu Eric.
Language: Javascript.
File: eric-ibu.js
=> commit for hngi7 stage 2 task

Tolulope-Kehinde.js, scripts/Tolulope-Kehinde.js
=> I added my file scripts

scripts/Ekor-Ibor.js
Sorry guys, I know you guys are doing a lot and wish I knew enough already to help.
I just made a slight change to remove some funny strings I added for space.
=> Updated Ekor-Ibor.js

scripts/Boluwatife-ojo.js
Please, I accept my pull request. Thanks
=> Tfeh's commitment 

scripts/James-OwusuAppiah.py
Make some changes to my code and removed the space in my name
=> Renamed and Updated file

scripts/abolade-kasope.js
=> Recent repo forked & email updated on my script

scripts/chimamanda.js
=> glory-onunwa.js

scripts/Alexander-Ugwuanyi.js
* Renamed my file from AlexanderUgwuanyi.js to Alexander-Ugwuanyi.js 
* Added 'and email ${email}'
=> AlexanderUgwuanyi.js to Alexander-Ugwuanyi.js

scripts/James-Owusu-Appiah.py
The file name was not right according to standard
=> Updated and renamed

scripts/omotayo-kasim.php
=> Update to omotayo-kasim.php

Okeke.Victor.js, scripts/Okeke.Victor.js
=> Okeke-Victor.js

scripts/Duru-young-Raymond.js
create my own script using javascript following the appropriate format.
=> chore: Create script

scripts/Ekor-Ibor.js
=> Changed the string template

James-Obongidiyake.js
Made a change to the script because of the name!
=> Name Change.

Demo-Images/Elusakin-Oluwanifemi.py
I have removed all the inner brackets. 
Please merge my edited file.
=> updated file 

scripts/folarin-oyenuga.js
Here is my script for the second task.
=> commit by Folarin Oyenuga

scripts/joshua-ogbonna.js
Please merge this project. I made a necessary correction. Thanks for your time.
=> Modified joshua-ogbonna.js

scripts/Okwuobi-Ifeanyi.js
Its all there, I finally know how to create pull requests. Adding my script to the script folder. Go team Sentry
=> added internScript Okwuobi-Ifeanyi.js to Script folder for stage two

scripts/Zephaniah Joshua HNG-06681.js
=> kzeph19-HNG-06681 script

scripts/Osiegbu Precious.py
=> Create Osiegbu Precious.py

scripts/Adeyemi-Matthew.py
=> Fixed Update Adeyemi-Matthew.py

scripts/susan-wangari.js
=> updated changes

scripts/ojo-temitope.js
Added the ojo-temitope.js file
=> created the js file

scripts/Ifediora-Adanma.js
=> black lives matter

scripts/annah-mweru-nichola.js
=> pilling for top 50

scripts/abdullahi.aliyu.js
Changed the id key id key type to string, prefixed `-` to `ID`
=> Made some changes

scripts/susan-wangari.js
=> a little change made

scripts/Chukwubuikem-Chiabotu.js
My script has been added into the script folder...
=> Uploaded My Script

scripts/Adeyemi-Matthew.py
Please this is my pull request
=> New Request

scripts/Sarah-Okenwa.js
=> Add scripts/Sarah-Okenwa.js

scripts/abdullahi-aliyu.js, scripts/abdullahi.aliyu.js
Changed console.log output to to use template literals
=> Update and rename abdullahi.aliyujs -> abdulahi-aliyu

scripts/Ihedioha-Chinedu.java
=> ChinexLatest

scripts/Ihedioha-Chinedu.java
=> AnotherLatest

scripts/Nsikak-Akpan.py
=> corrected commit .py

scripts/ikechukwu_chukwudi.py
=> update my email and script

scripts/Elusakin-Oluwanifemi.py
I just edited my file 
Please merge my edited file
=> edited file 

scripts/Dauda-Emmanuel.py
Made modification to the script.
=> Modified the code 

scripts/Samuel-Ajayi.js
function hng(name, id, language, email){
console.log(`Hello World, this is ${name} with HNGi7 ID ${id} and email ${email} using ${language} for stage 2 task`)
}
hng("Ajayi Samuel Toluwa", "HNG-00302", "JavaScript", "troysammie7@gmail.com" )
=> Samuel-Ajayi.js

scripts/david-adediji.py
=> david-adediji.py updated

scripts/Ikeche-Chikezie.py
Made changes using .format to parse variables
=> NEW UPDATE

scripts/abiodun-jacob.py
- added abiodun-jacob.py
- made corrections to misplaced email
=> Added abiodun-jacob.py

scripts/Herbert-Olinga.js
=> Addeing my Javascript

scripts/Ayoola-Fashina.js
=> this is my first commit

scripts/Adiele-Vera.js
I've tested my script and made changes.
=> Adiele-Vera.js

scripts/abdullahi-aliyu.js
=> Delete abdullahi-aliyu. Js

joseph-roland.py, scripts/joseph-roland.py
new correction made to my project
=> my stage2 project commit

scripts/Ayoola-Fashina.js
=> my first commit

scripts/Okwuobi-Ifeanyi.js
I have corrected the errors that prevented my script from passing thanks
=> corrected error in my Okwuobi-Ifeanyi.js it passes now

scripts/Emmanuel-abutu.js
=> Updated Emmanuel-Abutu.js

scripts/Alex-Nmesoma.js
=> Alex-Nmesoma.js

scripts/Ishaku-Emmanuel.js
here is my final corrected task for going to stage 2. God bless you all
=> Ishaku-Emmanuel corrected

scripts/Okwuobi-Ifeanyi.js
Thanks for all the surport kadetXx, Umar Go team sentry!
=> Errors corrected, it shows passing when run using my local server

olanrewaju-sule.php
mistakenly merged to root directory.
=> Revert "Create olanrewaju-sule.php"

scripts/Ododo-Peace.py, scripts/Ododo_Peace_O.py
=> Ododo-Peace edits

scripts/olanrewaju-sule.php
Moved file to script directory
=> olanrewaju-sule.php

scripts/Omowumi-Olusola.js
Please her email address was wrong, and it had been corrected. Thank you Kadet
=> Update her email address

scripts/Susan-Muteti.js
this a script that shows my name, email and hang id
=> this is an updated script.. pls merge it

scripts/Joseph-Uwadiale.js
Dear @Austino
Please add my file
Thanks
=> add Joseph-Uwadiale.js

scripts/ehighibe-kelechi.js
please i just uploaded my code for task 2
.
=> please test and merge
